import {test,expect} from '@playwright/test';
import {start,load,brief,toggle,memory,deliver,state,scene} from './helpers';
test('full street-level journey completes all three chapters with real repairs',async({page})=>{
 test.setTimeout(360000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.emulateMedia({reducedMotion:'no-preference'});await start(page);
 await page.evaluate(()=>{const issues=new Set<string>();(window as any).__contactIssues=issues;setInterval(()=>{const s=(window as any).__ENOUGH__.scene();if(s.mode==='delivery'){for(const who of ['pip','cart'])for(const contact of [...s.staticContacts[who],...s.ambientContacts[who]])issues.add(`${who} in chapter ${s.day+1}: ${contact}`);}},35);});
 await brief(page);await toggle(page,'mural');await toggle(page,'bakery');await deliver(page,false);expect((await state(page)).result.route).toBe('Garden passage');
 await page.locator('[data-action="next"]').click();await deliver(page,false);await expect(page.locator('.result-card')).toContainText('Cart too wide.');
 await page.locator('[data-action="repair"]').click();await page.locator('[data-action="toggle"]').click();await deliver(page,false);expect((await state(page)).result.route).toBe('Park path');
 await page.locator('[data-action="next"]').click();await deliver(page);expect((await state(page)).result.fact).toBe('park');
 await page.locator('[data-action="repair"]').click();await memory(page,'works');await page.locator('[data-action="refresh"]').click();await deliver(page,false);expect((await state(page)).result.route).toBe('Queen Street');
 await page.locator('[data-action="next"]').click();await expect(page.locator('.ending')).toContainText('Enough, for now.');expect((await state(page)).attempts).toHaveLength(5);expect(errors).toEqual([]);expect(await page.evaluate(()=>[...(window as any).__contactIssues])).toEqual([]);
});
test('WASD movement accelerates, stops on release, and blur clears input',async({page})=>{await start(page);const p=(await scene(page)).position;await page.keyboard.down('w');await page.waitForTimeout(900);expect((await scene(page)).position.x).toBeGreaterThan(p.x+.7);await page.keyboard.up('w');await page.waitForTimeout(600);expect((await scene(page)).speed).toBeLessThan(.1);await page.keyboard.down('d');await page.waitForTimeout(100);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect((await scene(page)).keys).toEqual([]);expect((await scene(page)).speed).toBeLessThan(.1);await page.keyboard.up('d');});
test('Shift rolls faster and diagonal movement has no speed bonus',async({page})=>{await start(page);expect((await scene(page)).camera.yaw).toBeCloseTo(1.95);await page.keyboard.down('Shift');await page.keyboard.down('w');await expect.poll(async()=>(await scene(page)).speed,{timeout:2500}).toBeGreaterThan(3);const fast=(await scene(page)).speed;expect(fast).toBeGreaterThan(3);await page.keyboard.down('d');await page.waitForTimeout(150);expect((await scene(page)).speed).toBeLessThan(3.45);await page.keyboard.up('w');await page.keyboard.up('d');await page.keyboard.up('Shift');});
test('mouse drag changes the camera; recenter and overview remain usable',async({page})=>{await start(page);const yaw=(await scene(page)).camera.yaw;await page.mouse.move(950,500);await page.mouse.down();await page.mouse.move(1150,550,{steps:8});await page.mouse.up();expect(Math.abs((await scene(page)).camera.yaw-yaw)).toBeGreaterThan(.8);await page.keyboard.press('r');expect((await scene(page)).camera.yaw).toBeCloseTo((await scene(page)).heading);await page.getByRole('button',{name:'Neighbourhood overview'}).click();await expect(page.locator('dialog')).toContainText('Queen East');await page.locator('[data-place=mercury]').click();expect((await scene(page)).position.x).toBeCloseTo(393);});
test('nearby E opens a detail and blocks movement while the brief is open',async({page})=>{await load(page,0);await page.keyboard.press('e');await expect(page.locator('.brief-drawer')).toBeVisible();await expect(page.locator('.memory-detail')).toContainText('Bonjour');const p=(await scene(page)).position;await page.keyboard.down('w');await page.waitForTimeout(400);await page.keyboard.up('w');expect((await scene(page)).position).toEqual(p);await page.keyboard.press('Escape');await expect(page.locator('.brief-drawer')).toBeHidden();});
test('four-memory limit, forgetting, and keyboard brief access',async({page})=>{await start(page);await page.keyboard.press('Tab');await memory(page,'gate');await page.locator('[data-action="toggle"]').click();await expect(page.locator('.toast')).toContainText('Brief full');expect(Object.keys((await state(page)).brief)).toHaveLength(4);await toggle(page,'mural');await toggle(page,'gate');expect((await state(page)).brief.gate.value).toBe('70');await page.keyboard.press('Escape');await page.keyboard.press('b');await expect(page.locator('.brief-drawer')).toBeVisible();});
for(const [name,ids,fact] of [['empty',[],'works'],['missing entrance',['works','gate'],'entrance'],['wide cart',['works','entrance'],'gate']] as const){test(`${name} brief fails honestly and can retry`,async({page})=>{await load(page,name==='wide cart'?1:0,[...ids]);await deliver(page);expect((await state(page)).result.fact).toBe(fact);await page.locator('[data-action="retry"]').click();expect((await state(page)).mode).toBe('explore');expect((await scene(page)).position.x).toBe(-14);});}
test('snow lucky success is distinguished from refreshed knowledge',async({page})=>{await load(page,2,['entrance']);await deliver(page);await expect(page.locator('.result-card')).toContainText('lucky guess');});
test('checking an unremembered condition does not silently add it',async({page})=>{await load(page,2,['entrance']);await brief(page);await memory(page,'works');await page.locator('[data-action="refresh"]').click();expect((await state(page)).brief.works).toBeUndefined();await page.locator('[data-action="toggle"]').click();expect((await state(page)).brief.works.version).toBe(2);});
test('pause, nested About, and resume preserve an active delivery',async({page})=>{await start(page);await page.locator('[data-action="send"]').click();await page.waitForTimeout(300);await page.locator('[data-action="pause"]').click();const p=(await scene(page)).position;await page.waitForTimeout(250);expect((await scene(page)).position).toEqual(p);await page.locator('[data-action="menu"]').click();await page.locator('[data-action="about"]').click();await expect(page.locator('dialog')).toContainText('The game explores intelligence');expect((await scene(page)).paused).toBe(true);await page.locator('.dialog-close').click();expect((await scene(page)).paused).toBe(true);await page.locator('[data-action="pause"]').click();await page.waitForTimeout(250);expect((await scene(page)).position).not.toEqual(p);await page.locator('[data-action="skip"]').click();await expect(page.locator('.result-card.success')).toBeVisible();});
test('cancel discards an active attempt and double send cannot duplicate it',async({page})=>{await start(page);await page.locator('[data-action="send"]').dblclick();await page.locator('[data-action="cancel"]').click();await page.waitForTimeout(250);expect((await state(page)).attempts).toHaveLength(0);expect((await state(page)).mode).toBe('explore');await deliver(page);expect((await state(page)).attempts).toHaveLength(1);});
test('saved progress reloads, chapter replay resets facts, restart needs its own confirmation',async({page})=>{await start(page);await brief(page);await toggle(page,'mural');await toggle(page,'bakery');await deliver(page);await page.locator('[data-action="next"]').click();await page.reload();await page.locator('[data-action="resume"]').click();expect((await state(page)).chapter).toBe(1);expect(Object.keys((await state(page)).brief)).toHaveLength(2);await page.locator('[data-action="chapter"][data-chapter="0"]').click();expect(Object.keys((await state(page)).brief)).toHaveLength(4);await page.locator('[data-action="menu"]').click();await page.locator('[data-action="reset"]').click();await expect(page.locator('dialog')).toContainText('This resets');await page.locator('[data-action="confirm-reset"]').click();expect((await state(page)).unlocked).toBe(0);});
test('corrupted or unavailable storage does not prevent playing',async({page})=>{await page.addInitScript(()=>{localStorage.setItem('enough-queen-east-v1','invalid JSON');Storage.prototype.setItem=()=>{throw new Error('unavailable')};});await start(page);await expect(page.locator('[data-action="resume"]')).toHaveCount(0);await deliver(page);await expect(page.locator('.result-card.success')).toBeVisible();});
test('audio is opt-in, unlocks on click, follows movement and mutes',async({page})=>{
 const sound=()=>page.evaluate(()=>(window as any).__ENOUGH__.sound());
 await start(page);expect((await sound()).state).toBe('uninitialized');
 await page.getByRole('button',{name:'Enable sound'}).click();
 await expect.poll(async()=>(await sound()).state).toBe('running');
 await page.keyboard.down('w');
 // Web Audio starts on its own clock. Verify movement and the gain ramp,
 // rather than assuming both completed in a fixed 700 ms wall-clock sleep.
 await expect.poll(async()=>(await scene(page)).speed,{timeout:3000}).toBeGreaterThan(1);
 await expect.poll(async()=>(await sound()).motorGain,{timeout:3000}).toBeGreaterThan(.005);
 await page.keyboard.up('w');await page.getByRole('button',{name:'Mute sound'}).click();
 await expect.poll(async()=>(await sound()).masterGain,{timeout:3000}).toBeLessThan(.001);
});
test('reduced motion keeps normal travel speed and offers explicit skip',async({page})=>{await start(page);expect((await scene(page)).reducedMotion).toBe(true);await page.locator('[data-action="send"]').click();await page.waitForTimeout(450);expect((await scene(page)).speed).toBeLessThan(8);await page.locator('[data-action="skip"]').click();await expect(page.locator('.result-card.success')).toBeVisible();});
for(const size of [{width:1280,height:720},{width:1920,height:1080}]){test(`canvas fills ${size.width}×${size.height} and brief fits`,async({page})=>{await page.setViewportSize(size);await start(page);const canvas=await page.locator('canvas').boundingBox();expect(canvas?.width).toBe(size.width);expect(canvas?.height).toBe(size.height);await brief(page);const drawer=await page.locator('.brief-drawer').boundingBox();expect(drawer!.y).toBeGreaterThan(0);expect(drawer!.y+drawer!.height).toBeLessThanOrEqual(size.height);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});}
for(const chapter of [1,2])test(`cart chapter ${chapter+1} spawns clear and can explore`,async({page})=>{await load(page,chapter);const initial=await scene(page);await page.keyboard.down('w');await page.waitForTimeout(850);await page.keyboard.up('w');const moved=await scene(page);expect(moved.position.x).toBeGreaterThan(initial.position.x+.7);expect(moved.cart.x).toBeGreaterThan(initial.cart.x+.6);});
test('restarting a paused delivery does not leave exploration paused',async({page})=>{await start(page);await page.locator('[data-action="send"]').click();await page.locator('[data-action="pause"]').click();await page.locator('[data-action="menu"]').click();await page.locator('[data-action="reset"]').click();await page.locator('[data-action="confirm-reset"]').click();await page.waitForTimeout(100);expect((await scene(page)).paused).toBe(false);await page.keyboard.down('w');await page.waitForTimeout(600);await page.keyboard.up('w');expect((await scene(page)).position.x).toBeGreaterThan(-870.7);});
test('no-route briefing fails immediately with a useful repair',async({page})=>{await load(page,2,['works','entrance','gate','park'],['park']);await deliver(page,false);expect((await state(page)).result.route).toBe('No route');await expect(page.locator('.result-card')).toContainText('Every route');await page.locator('[data-action="repair"]').click();await page.locator('[data-action="refresh"]').click();await deliver(page);expect((await state(page)).result.success).toBe(true);});
test('repeated trips dispose route geometry instead of accumulating it',async({page})=>{await start(page);await deliver(page);await page.waitForTimeout(150);const baseline=(await scene(page)).geometries;for(let i=0;i<5;i++){await page.locator('[data-action="retry"]').click();await deliver(page);}await page.waitForTimeout(150);expect((await scene(page)).geometries).toBeLessThanOrEqual(baseline+2);});

test('all mapped landmark visits leave the wide cart clear of architecture',async({page})=>{test.setTimeout(70000);await load(page,1);await page.locator('[data-action=map]').click();const ids=await page.locator('[data-place]').evaluateAll(els=>els.map(el=>el.getAttribute('data-place')!));expect(ids).toHaveLength(40);expect(ids).toEqual(expect.arrayContaining(['studio535','degrassi-bend','degrassi-west-row','stone-pair','butchers','boulton-mural','queen-graffiti']));await page.locator('.dialog-close').click();for(const id of ids){await page.locator('[data-action=map]').click();await page.locator(`[data-place="${id}"]`).click();expect((await scene(page)).staticContacts, id).toEqual({pip:[],cart:[]});}});
test('landmark travel is unavailable during a delivery and returns after cancellation',async({page})=>{await start(page);await page.locator('[data-action=send]').click();await expect(page.locator('[data-action=map]')).toBeDisabled();await page.locator('[data-action=cancel]').click();await expect(page.locator('[data-action=map]')).toBeEnabled();await page.locator('[data-action=map]').click();await page.locator('[data-place=carlaw]').click();expect((await scene(page)).position.x).toBe(494);});

test('the actual CN Tower SkyPod and antenna are visible from the southwest bridge view',async({page})=>{await start(page);await page.locator('[data-action=map]').click();await page.locator('[data-place=cn-skyline]').click();await expect.poll(async()=>{const sky=await page.evaluate(()=>(window as any).__ENOUGH__.skyline());return sky.samples.filter((s:any)=>s.height>=447).every((s:any)=>!s.occluded&&Math.abs(s.ndc[0])<.8&&Math.abs(s.ndc[1])<.85&&s.ndc[2]<1);}).toBe(true);await page.screenshot({path:`${process.env.EVIDENCE_DIR||'evidence/v5'}/cn-skyline.png`});});
