import {test} from 'node:test';import assert from 'node:assert/strict';
import {GEO,project,inside,START} from '../src/geography';import {blocked,moveWithCollision} from '../src/motion';import * as T from 'three';
const point=(id:string)=>GEO.pois.find(p=>p.id===id)!.point;
test('endpoints retain the real King/River and Queen/Carlaw coordinates and metre scale',()=>{assert(Math.hypot(point('king-river')[0]-START[0],point('king-river')[1]-START[1])<8);const d=Math.hypot(point('carlaw')[0]-point('king-river')[0],point('carlaw')[1]-point('king-river')[1]);assert(d>1370&&d<1390);assert(Math.hypot(...project(-79.3460724,43.6597243))<.001);});
test('verified businesses retain correct Queen-side and east/west ordering',()=>{const keys=['dark-horse','broadview','opera','amber','bonjour','queen-books','mercury'];for(let i=1;i<keys.length;i++)assert(point(keys[i])[0]>point(keys[i-1])[0]);for(const id of ['dark-horse','bonjour','queen-books','amber'])assert(point(id)[1]<0);for(const id of ['opera','mercury'])assert(point(id)[1]>0);assert(point('amber')[1]<-30);});
test('Jimmie Simpson uses its real north-of-Queen polygon, including its long northward extent',()=>{const park=GEO.areas.find(a=>a.id===24399322)!;assert.equal(park.name,'Jimmie Simpson Park');assert(park.p.every(p=>p[1]<-6));assert(Math.min(...park.p.map(p=>p[1]))< -330);assert(inside([151,-67],park.p));});
test('the curved De Grassi alignment and mapped Don River are retained',()=>{const degrassi=GEO.roads.filter(r=>r.name==='De Grassi Street').flatMap(r=>r.p);assert(degrassi.some(p=>p[1]<-150));assert(degrassi.some(p=>p[0]>20));const river=GEO.areas.find(a=>a.id===244111750)!;assert(inside([-698,0],river.p));});
test('every imported building polygon and courtyard triangulates without a renderer crash',()=>{assert(GEO.buildings.length>700);for(const b of GEO.buildings){const s=new T.Shape(b.p.map(p=>new T.Vector2(p[0],-p[1])));for(const h of b.holes)s.holes.push(new T.Path(h.map(p=>new T.Vector2(p[0],-p[1]))));const g=new T.ExtrudeGeometry(s,{depth:b.h,bevelEnabled:false});assert(g.getAttribute('position').count>0,`empty ${b.id}`);g.dispose();}});
test('concave footprint collision leaves a real courtyard accessible',()=>{const p:[number,number][]=[[0,0],[5,0],[5,1],[1,1],[1,5],[0,5]];const o={x:2.5,z:2.5,w:5,d:5,h:4,p};assert(!blocked(3,3,.225,[o]));assert(blocked(.5,3,.225,[o]));assert(moveWithCollision([-1,3],[3,0],.225,[o])[0]<0);});

test('courtyard holes are not treated as solid building volume by trailer clearance',()=>{const o={x:0,z:0,w:12,d:12,h:5,p:[[-6,-6],[6,-6],[6,6],[-6,6]] as [number,number][],holes:[[[-3,-3],[-3,3],[3,3],[3,-3]]] as [number,number][][]};assert(!blocked(0,0,.48,[o]));assert(blocked(2.8,0,.48,[o]));assert(blocked(4,0,.48,[o]));});

test('the Broadview street edge belongs to the hotel rather than a thin piece of the adjacent row',()=>{const at=GEO.buildings.filter(b=>inside([-334,-9.1],b.p));assert.equal(at.length,1);assert(at[0].landmarks?.includes('broadview'));const neighbour=GEO.buildings.find(b=>b.buildingId===at[0].buildingId&&!b.landmarks);assert(neighbour);assert(neighbour.bounds[2]<=-341.79);});
