import {spawnSync} from 'node:child_process';import {readFile,writeFile,mkdir} from 'node:fs/promises';
const dir=process.env.FILM_DIR||'evidence/trailer',file=process.env.FILM_FILE||`${dir}/just-enough-trailer-web.mp4`;
const probe=JSON.parse(spawnSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}).stdout),v=probe.streams.find(s=>s.codec_type==='video');
const w=192,h=108,size=w*h,decode=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-i',file,'-vf',`scale=${w}:${h},format=gray`,'-f','rawvideo','pipe:1'],{maxBuffer:128*1024*1024});if(decode.status)throw Error(String(decode.stderr));
const bytes=decode.stdout,frames=bytes.length/size,diffs=[],black=[];let exactRun=0,longestExact=0,quietRun=0,longestQuiet=0;
for(let i=0;i<frames;i++){let luminance=0,diff=0;for(let j=0;j<size;j++){const value=bytes[i*size+j];luminance+=value;if(i)diff+=Math.abs(value-bytes[(i-1)*size+j]);}if(luminance/size<3)black.push(i/30);if(i){const mean=diff/size;diffs.push(mean);exactRun=mean===0?exactRun+1:0;quietRun=mean<.04?quietRun+1:0;longestExact=Math.max(longestExact,exactRun);longestQuiet=Math.max(longestQuiet,quietRun);}}
let seam=0;for(let j=0;j<size;j++)seam+=Math.abs(bytes[j]-bytes[(frames-1)*size+j]);seam/=size;
const sorted=[...diffs].sort((a,b)=>a-b),edit=JSON.parse(await readFile(`${dir}/edit.json`,'utf8')),capture=JSON.parse(await readFile(`${dir}/capture.json`,'utf8')),game=JSON.parse(await readFile(`${dir}/gameplay-report.json`,'utf8'));
const checks={fullHD:v.width===1920&&v.height===1080,fps30:v.r_frame_rate==='30/1',noBlackFrames:!black.length,noRepeatedFrozenRun:longestExact<15,loopSeam:seam<Math.max(3,sorted[Math.floor(sorted.length*.95)]),modernFontsLoaded:edit.fontProof.every(p=>p.loaded),cinematicRender:capture.samples.every(p=>p.scene.canvas.width===3840),noBrowserErrors:!capture.errors.length&&!game.errors.length,noSampledRobotCollisions:capture.samples.every(p=>!p.scene.staticContacts.pip.length&&!p.scene.ambientContacts.pip.length),genuineSuccessfulDelivery:game.samples.filter(p=>p.name==='10-delivered').every(p=>p.state.result?.success),correctURL:edit.shots.some(p=>p.html.includes('murch.org/justenough'))};
const report={checks,file,duration:Number(probe.format.duration),bytes:Number(probe.format.size),frames,width:v.width,height:v.height,fps:v.r_frame_rate,pixelFormat:v.pix_fmt,colorRange:v.color_range,blackFrames:black,longestIdenticalSeconds:longestExact/30,longestNearStillSeconds:longestQuiet/30,meanDifferenceAtLoop:seam,medianFrameDifference:sorted[Math.floor(sorted.length*.5)],p95FrameDifference:sorted[Math.floor(sorted.length*.95)],notes:['Near-still periods may be deliberate brief inspection; they are not evidence of an encoder freeze.','Frame continuity is measured on every decoded frame. Visual framing and architecture also require human/model review.','Actual gameplay; travel is shortened using the game’s existing Skip travel control.','Silent by design for looping web and sound-off social playback.']};
await mkdir(dir,{recursive:true});await writeFile(`${dir}/technical-report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(Object.values(checks).some(v=>!v))process.exitCode=1;
