import raw from './data/street-detail.json';
import {VIDEO_UNIT_ADDRESSES,VIDEO_SOURCE} from './video-data';
import type {Point} from './game';
export type Footprint={p:Point[];holes:Point[][];bounds:number[]};
export type StreetUnit=Footprint&{id:number;address:string;number:string;street:string;h:number;front:Point;yaw:number;width:number;depth:number;setback:number;evidence:string};
export const STREET=raw as unknown as {roads:{id:number;name:string;p:Point[];kind:string}[];units:StreetUnit[];remainders:Record<string,Footprint[]>;north:(Footprint&{id:number;h:number})[];surfaces:(Footprint&{id:number;kind:string})[];yards:(Footprint&{id:number;address:string})[];objects:Record<string,{id:number;p:Point;h:number;kind:string}[]>};
export type ElevationProfile={family:'shop'|'gable'|'flat-house'|'cottage'|'modern-house'|'gambrel'|'bay-gable'|'mansard'|'porch-gable'|'stucco-gable'|'bend-terrace'|'degrassi-row'|'degrassi-victorian';floors:number;eave:number;roof:number;brick:number;trim:number;door:number;windows:number;garden?:boolean;entrySide?:number;cladding?:'siding'|'stucco';blankSide?:boolean;frontColor?:number;sharedGable?:boolean;gableStyle?:'brick'|'timber';source?:string;note?:string};
// Only the entries with a source are individually observed. The remainder is
// parcel-resolved support geometry, explicitly unverified in the audit file.
const bia='https://riverside-to.com/riverside-architecture-tour/';
const boulton='https://www.google.com/maps/@43.6601634,-79.3469597,3a,75y,285h,95t/data=!3m4!1e1!3m2!1sDqZQ-vJwd0IaYz5nBwsIuw!2e0';
const degrassi='https://www.google.com/maps/@43.661163,-79.3463432,3a,90y,275h,90t/data=!3m4!1e1!3m2!1sX_4jqMTdsGM6ATnl52KSWg!2e0';
const degrassi90='https://www.google.com/maps/@43.6621836,-79.3468205,3a,95y,255h,90t/data=!3m4!1e1!3m2!1s7H-J1zdV2zoCUsN4dCHrAw!2e0';
const degrassiBend='https://www.google.com/maps/@?api=1&map_action=pano&pano=-vIEdscZhJ2Om8mXh18Tbg&heading=285&pitch=12&fov=100';
const explicit:Record<string,Partial<ElevationProfile>>={
 '730 Queen St E':{floors:2,eave:8.3,roof:.3,source:VIDEO_SOURCE,note:'Video reference: Lamoon black fascia, gold lettering; upper level partly out of frame.'},
 '732 Queen St E':{floors:2,eave:8.3,roof:.3,source:VIDEO_SOURCE,note:'Video reference: black timber storefront and red/black graffiti plinth east of Lamoon. Upper openings remain approximate.'},
 '734 Queen St E':{floors:2,eave:8.3,roof:2.4,source:VIDEO_SOURCE,note:'Video reference: sloping roof and small dark-trimmed dormers west of Butchers.'},
 '736 Queen St E':{floors:2,eave:8.3,roof:2.4,source:VIDEO_SOURCE,note:'Video reference: continued dormer roof and cream masonry details.'},
 '738 Queen St E':{floors:3,eave:13.2,roof:.3,source:VIDEO_SOURCE,note:'Video reference: Butchers navy/gold fascia and navy canopy; projecting second-storey bays, round-headed top windows and terracotta rosettes.'},
 '740 Queen St E':{floors:3,eave:13.2,roof:.3,source:VIDEO_SOURCE,note:'Video reference: St. John’s eco Market cream/red fascia; same ornate red-brick block. Eye-painted entry pier visible.'},
 '742 Queen St E':{floors:3,eave:13.2,roof:.3,source:VIDEO_SOURCE,note:'Video reference: eastern continuation of ornate brick upper front; ground shop identity not assigned.'},
 '800 Queen St E':{floors:2,eave:8.0,roof:.25,brick:0xb6aaa0,source:VIDEO_SOURCE,note:'Video reference: Tim Hortons grey/taupe corner, cream window borders and BISKAABIIYAANG mural on west wall.'},

 '11 Boulton Ave':{family:'flat-house',floors:2,eave:7.2,roof:.25,cladding:'stucco',brick:0xb6a28e,trim:0x8a8271,source:VIDEO_SOURCE,note:'Video reference: flat service building with long painted masonry lane wall, irregular windows and doors; west front stone clad. Lane elevation authored separately.'},
 '12 De Grassi St':{family:'bend-terrace',floors:2,eave:7.35,roof:.75,brick:0xc9977b,frontColor:0xdeddd3,trim:0x2e3532,door:0x202a27,windows:2,entrySide:1,blankSide:true,source:degrassiBend,note:'April 2026: white-painted front, paired narrow windows, right-hand raised dark steps, dark cornice, white gravel garden. Exposed red-brick lane wall has no repeated sash-window grid. Roof behind the visible cornice is approximate.'},
 '14 De Grassi St':{family:'bend-terrace',floors:2,eave:7.35,roof:.8,brick:0xc3b496,trim:0x303831,door:0x242d29,windows:2,garden:true,source:degrassiBend,note:'April2026 pale irregular-stone frontage and raised entrance. The newer192s video locates the shared gable over16/18;14 uses a conservative shallow roof. Hidden details remain approximate.'},
 '16 De Grassi St':{family:'bend-terrace',floors:2,eave:7.35,roof:2.45,sharedGable:true,brick:0xc5bba5,trim:0x293540,door:0x26323b,windows:2,garden:true,entrySide:1,source:VIDEO_SOURCE,note:'Video reference: visible number16, pale rubble stone, two tall ground windows with white flower boxes, dark navy raised door and canopy. One gable crosses the party line above the paired16/18 entrances.'},
 '18 De Grassi St':{family:'bend-terrace',floors:2,eave:7.35,roof:.8,brick:0xc5bba5,trim:0x293540,door:0x26323b,windows:2,garden:true,entrySide:-1,source:VIDEO_SOURCE,note:'Video reference: adjoining half of the stone pair. Paired glazed door beside16 under shared gable. Red Japanese maple and dense planting. Hidden roof remains approximate.'},
 '20 De Grassi St':{family:'degrassi-row',floors:2,eave:7.05,roof:2.05,brick:0xd2a68b,trim:0x293b3a,door:0x283437,windows:2,garden:true,entrySide:1,gableStyle:'brick',source:VIDEO_SOURCE,note:'Video reference: buff brick accents around dark tall sash windows; garden largely concealed by a columnar evergreen. Door placement partly occluded.'},
 '22 De Grassi St':{family:'degrassi-row',floors:2,eave:7.05,roof:2.05,brick:0xd4b09b,trim:0x293b3a,door:0x283437,windows:2,garden:true,entrySide:-1,gableStyle:'brick',source:VIDEO_SOURCE,note:'Video reference: steep red-brick gable and dark trim, deep planted frontage. Partly obscured; address association follows the sequence south of visibly numbered24.'},
 '24 De Grassi St':{family:'degrassi-row',floors:2,eave:7.05,roof:2.05,brick:0xd9b39f,trim:0x293b3a,door:0x283437,windows:2,garden:true,entrySide:1,gableStyle:'brick',source:VIDEO_SOURCE,note:'Video reference: number24 above right-hand black door, left tall sash, broad raised black timber porch and stairs, plain brick gable without an attic window.'},
 '26 De Grassi St':{family:'degrassi-row',floors:2,eave:7.05,roof:2.05,brick:0xd8b29a,trim:0x293b3a,door:0x283437,windows:2,garden:true,entrySide:1,gableStyle:'timber',source:VIDEO_SOURCE,note:'Video reference: window with pale blind left of navy door, brick porch pier, dark bargeboard and green infill in the front gable; address follows24/28 anchors.'},
 '28 De Grassi St':{family:'degrassi-row',floors:2,eave:7.05,roof:2.05,brick:0xd9b39c,trim:0x293b3a,door:0x283437,windows:2,garden:true,entrySide:-1,gableStyle:'timber',source:VIDEO_SOURCE,note:'Video reference: visible number28, left entrance, natural timber stairs and rails, brick porch pier, dark green gable infill and narrow upper sash windows.'},
 '30B De Grassi St':{family:'degrassi-victorian',floors:2,eave:7.6,roof:2.45,brick:0xd3b09c,trim:0xc4c4aa,door:0x343f3c,windows:2,garden:true,entrySide:1,source:VIDEO_SOURCE,note:'Video reference: taller brick group north of28, pale horizontal stone bands, arched entrance surrounds, tall upper windows and steep gables. City parcel association; vegetation conceals some openings and proportions remain estimated.'},
 '32 De Grassi St':{family:'degrassi-victorian',floors:2,eave:7.6,roof:2.45,brick:0xd3b09c,trim:0xc4c4aa,door:0x343f3c,windows:2,garden:true,entrySide:1,source:VIDEO_SOURCE,note:'Video reference: taller brick group north of28, pale horizontal stone bands, arched entrance surrounds, tall upper windows and steep gables. City parcel association; vegetation conceals some openings and proportions remain estimated.'},
 '34 De Grassi St':{family:'degrassi-victorian',floors:2,eave:7.6,roof:2.45,brick:0xd3b09c,trim:0xc4c4aa,door:0x343f3c,windows:2,garden:true,entrySide:1,source:VIDEO_SOURCE,note:'Video reference: taller brick group north of28, pale horizontal stone bands, arched entrance surrounds, tall upper windows and steep gables. City parcel association; vegetation conceals some openings and proportions remain estimated.'},
 '90 De Grassi St':{family:'mansard',floors:2,eave:3.25,roof:2.65,brick:0xcac7b6,trim:0xe0dfd0,door:0xe4e3d8,windows:1,garden:true,entrySide:1,cladding:'siding',source:degrassi90,note:'September 2021: cream siding, right-hand glazed door, broad box dormer, shallow shingled mansard and white stair rail. Number visible in panorama; plan from City parcel.'},
 '90A De Grassi St':{family:'mansard',floors:2,eave:3.25,roof:2.65,brick:0xc9bea0,trim:0xe2dfce,door:0x17375b,windows:1,garden:true,cladding:'siding',source:degrassi90,note:'Blue left-hand glazed door and circular 90A plaque, yellow/cream clapboard, broad upper casement in box dormer, black stair railing.'},
 '90 1/2 De Grassi St':{family:'stucco-gable',floors:2,eave:5.7,roof:1.45,brick:0xb9bab5,trim:0xe0ddd0,door:0x414944,windows:1,garden:true,entrySide:1,cladding:'stucco',source:degrassi90,note:'90½ is visibly numbered: narrow grey stucco front, centered paired upper casement, low cedar garden screen; proportions approximate.'},
 '92 De Grassi St':{family:'porch-gable',floors:2,eave:6.1,roof:2.45,brick:0xb8a695,trim:0x363c37,door:0x4d392b,windows:1,garden:true,source:degrassi90,note:'Next property north of visibly numbered 90½: red brick, dark projecting upper bay, half-timber gable and full-width dark timber porch; City parcel association.'},
 '94 De Grassi St':{family:'porch-gable',floors:2,eave:6.1,roof:2.45,brick:0xcfb6a0,trim:0xa2a99e,door:0x564638,windows:1,garden:true,source:degrassi90,note:'Adjacent brick gable and upper bay with pale grey trim; ground floor partly obscured by vegetation. Porch and unobserved details approximate.'},
 '48 De Grassi St':{family:'gambrel',floors:2,eave:3.45,roof:3.35,brick:0xb7aea0,trim:0xe2dfd1,door:0x292f2d,windows:2,garden:true,source:degrassi,note:'September 2021: gambrel-shaped front roof, two paired upper casements, projecting porch/bay below; address resolved from City parcel and address points.'},
 '54 De Grassi St':{family:'bay-gable',floors:2,eave:6.05,roof:2.95,trim:0xc8b78b,brick:0xd1ab99,windows:2,garden:true,source:degrassi,note:'Steep red gable, tall projecting two-level bay and ivy; address resolved from City parcel and address points.'},
 '56 De Grassi St':{family:'bay-gable',floors:2,eave:6.05,roof:2.70,trim:0x655f47,brick:0xb9a394,windows:2,garden:true,source:degrassi,note:'Dark bargeboard beside 54, narrow two-level bay; address resolved from City parcel and address points.'},
 '52 De Grassi St':{family:'cottage',floors:1,eave:3.55,roof:2.5,brick:0xe2c1a8,trim:0xf0eee1,door:0xdadfd3,windows:2,garden:true,source:bia,note:'One-storey central Gothic gable, carved white bargeboard, oval-glazed door; City envelope incorrectly suggested 10.28 m.'},
 '8 Boulton Ave':{family:'flat-house',floors:2,eave:7.1,roof:.3,door:0x2b4566,windows:2,source:boulton},
 '10 Boulton Ave':{family:'flat-house',floors:2,eave:7.1,roof:.3,door:0xc0a546,windows:2,source:boulton},
 '12 Boulton Ave':{family:'cottage',floors:1,eave:3.65,roof:1.3,windows:1,source:'https://arearealtor.com/property-details/12-boulton-avenue-toronto-on-e13418898',note:'Cottage street face; deeper two-storey addition is not implied by the front roof.'},
 '14 Boulton Ave':{family:'flat-house',floors:2,eave:6.7,roof:.3,trim:0x53616b,door:0x96544a,source:boulton,note:'Slate-coloured upper cladding, brick ground floor, shallow door canopy.'},
 '16 Boulton Ave':{family:'flat-house',floors:2,eave:6.7,roof:.3,trim:0x53616b,door:0x272e32,source:boulton},
 '18 Boulton Ave':{family:'cottage',floors:1,eave:3.4,roof:1.25,brick:0xf0ece0,trim:0xd8d9cb,windows:1,source:boulton},
 '20 Boulton Ave':{family:'gable',floors:2,eave:6.2,roof:2.1,trim:0xe1d3a9,source:boulton},
 '70 Boulton Ave':{family:'modern-house',floors:3,eave:9.55,roof:.55,brick:0x555b5c,trim:0x636b70,door:0x30383b,source:'https://halyardgroup.ca/wp-content/uploads/2026/06/new108-68-Boulton-Ave.jpg',note:'Charcoal-clad next unit north of the visibly numbered 68.'},
 '66 Boulton Ave':{family:'modern-house',floors:3,eave:9.55,roof:.55,brick:0xe6bba2,trim:0x626a6f,source:'https://halyardgroup.ca/wp-content/uploads/2026/06/new108-68-Boulton-Ave.jpg'},
 '68 Boulton Ave':{family:'modern-house',floors:3,eave:9.55,roof:.55,brick:0xf4ccb3,trim:0x4b5256,door:0x35393c,source:'https://halyardgroup.ca/wp-content/uploads/2026/06/new108-68-Boulton-Ave.jpg',note:'Modern red brick, grey metal-framed paired glazing and deep cedar soffit; not a Victorian gable.'},
};
export function elevation(u:StreetUnit):ElevationProfile{
 const queen=u.street==='Queen St E',n=parseInt(u.number),floor=queen?Math.max(1,Math.min(3,Math.round(u.h/3.65))):u.h<6?1:2;
 const p:ElevationProfile={family:queen?'shop':floor===1?'cottage':'gable',floors:floor,eave:queen?floor*3.25+.55:floor*2.85+.55,roof:queen?.25:1.9,brick:0xe2c5ad,trim:0xd8d4c3,door:0x3f4947,windows:Math.max(1,Math.round(u.width/(queen?2.65:3.1)))};
 // Plan data matches the modern townhouse row photographed at 66–70; the
 // rest of the row's exact colours are an inference, tracked in the report.
 if(u.street==='Boulton Ave'&&n>=50&&n<=74&&n%2===0)Object.assign(p,{family:'modern-house',floors:3,eave:9.5,roof:.55,brick:(Math.floor(n/4)%2)?0xf0c8af:0x565b5d,trim:0x53595b,note:'Modern row family; only 68 individually photo-reviewed.'});
 if(queen&&n>=686&&n<=698&&n%2===0)Object.assign(p,{floors:2,eave:7.7});
 if(u.address==='772 Queen St E')Object.assign(p,{floors:1,eave:7.1,brick:0xb6b8ad,trim:0xb8bcaf,note:'Video-observed low grey retail fascia; City roof union is not the front elevation.'});
 if(queen&&n>=916&&n<=932&&n%2===0)Object.assign(p,{floors:n===924?1:2,eave:n===924?4.1:7.1});
 if(VIDEO_UNIT_ADDRESSES.has(u.address))Object.assign(p,{floors:u.number==='893'?3:2,eave:u.number==='893'?13.6:u.number==='904'?9.88:7.5,roof:.20,source:VIDEO_SOURCE,note:'reference collection video-informed ground storefront. Upper profiles on the north shop row are only partially visible and remain approximate.'});
 return {...p,...explicit[u.address]};
}
