// Mike's reference collection recordings. Times refer to the SDR frame index in
// private reference archive (not distributed) Plans retain City/OSM registration; dimensions inferred
// from perspective video are estimates, never a calibrated survey.
import type {Point} from './game';
export const VIDEO_MASS_IDS=new Set([2969430,4217140,4372210,4434450]);
// The City's roof union4372210 combines the old corner and fragments of the
// new block. OSM traces two separate ground footprints. The37m frontage of899
// is independently corroborated by Toronto's2016 site plan (pages19–20).
export const VIDEO_GROUND={
 corner:{osm:837428517,p:[[331.35,10.14],[313.98,9.94],[311.83,12.68],[311.89,28.68],[318.65,28.76],[322.5,28.81],[322.51,17.54],[325.07,17.5],[324.94,31.09],[324.74,50.64],[330.08,50.47],[330.08,42.38],[330.09,39.9],[330.09,29.22],[330.92,29.04],[331.28,14.08],[331.35,10.83]] as Point[],h:13.8},
 logan:{osm:837428516,p:[[331.35,10.83],[331.28,14.08],[330.92,29.04],[330.09,29.22],[330.09,39.9],[330.08,42.38],[330.08,50.47],[366.75,50.69],[366.91,47.25],[366.96,42.41],[366.99,39.84],[367.25,13.96],[367.29,10.71],[333.33,10.82]] as Point[],h:20.0},
};
export const VIDEO_UNIT_ADDRESSES=new Set(['730 Queen St E','732 Queen St E','734 Queen St E','736 Queen St E','738 Queen St E','740 Queen St E','742 Queen St E','800 Queen St E','884 Queen St E','888 Queen St E','890 Queen St E','892 Queen St E','894 Queen St E','896 Queen St E','898 Queen St E','900 Queen St E','904 Queen St E','893 Queen St E']);
export const VIDEO_HEIGHTS:Record<number,number>={2969430:24.2,4217140:12.2,4372210:13.8,4434450:15.76};
export const VIDEO_SOURCE='Photo and video references — Mike Murchison (@mimurchison)';
export const VIDEO_OBSERVATIONS=[
 {id:'oct4-poulton',frames:['Video reference','Video reference','Video reference','Video reference'],place:'Queen / Boulton, Poulton Block and798entrance',observed:'Dark paired frames, three-circle fanlights in the middle-storey arches, black shop piers, St.Mary Pharmacy / PharmaChoice fascia, Chez Nous at798, bronze door trim, two rounded pale entrance steps and slatted side planters.',limits:'Dimensions estimated from perspective; upper masonry retains the older public-domain reference. Door opening, interiors and temporary construction are not reconstructed from the people in the recording.'},
 {id:'oct4-east-park',frames:['Video reference','Video reference','Video reference','Video reference','Video reference','Video reference'],place:'East from the rail underpass along the north sidewalk past Jimmie Simpson Park',observed:'River of Life mural on the opposite south wall, recreation-centre brick inscription wall, worn lawn, broad mature trees, slight ground variation, separate western blue-post park sign and coloured park bench.',limits:'Blue sign lettering and bench geometry are modeled; artwork and detailed recreation-centre inscription wall are still incomplete. Lawn boundaries follow clipped City/OSM polygons. Fine root elevations are not measured from video.'},
 {id:'oct4-booth-return',frames:['Video reference','Video reference','Video reference','Video reference','Video reference','Video reference','Video reference'],place:'Booth/Logan view and westbound return to Bonjour Brioche',observed:'Westward views of the retained south apartments, north shop sequence, yellow awning near Booth, cross-track drain, rail-groove concrete panels, repaired asphalt and the blue Bonjour Brioche canopy on return.',limits:'Confirms earlier storefront ordering. The cross-track drain is placed approximately from perspective. Spatial footage is decoded as SDR reference frames, not calibrated stereo depth or photogrammetry.'},
 {id:'degrassi-west-row-2026',frames:['Video reference','Video reference','Video reference','Video reference','Video reference'],place:'20–34 De Grassi, west side facing north',observed:'Number24 above a right-hand door and28 beside a left-hand door. Connected red-brick row with roof ridges parallel to the street, blank brick gables at the southern end, green infill gables farther north, raised timber porches and contrasting natural-wood stairs at28. Taller northern group has pale bands and arched entrances. Columnar evergreen and dense planting beside the stone pair.',limits:'24 and28 numbers are visible. Other frontage identities follow City parcel sequence. Foliage and cars obscure some lower openings. Dimensions and hidden elevations remain estimates.'},
 {id:'butchers-block',frames:['Video reference','Video reference','Video reference'],place:'730–742 Queen E',observed:'Butchers navy/gold shop and canopy, St. John’s eco Market cream/red fascia, projecting upper bays, round-headed windows, rosettes and west dormers. Red/black graffiti on732 plinth; Lamoon730 identity corroborated by Riverside BIA.',limits:'Upper portions cropped out in close views; hidden elevations, exact dimensions and most interiors remain inferred.'},
 {id:'boulton-mural',frames:['Video reference','Video reference','Video reference','Video reference','Video reference'],place:'800 Queen E / 4 Boulton',observed:'Tim Hortons grey/taupe corner, cream upper trim and black stringcourses. Portions of Que Rock’s2024 BISKAABIIYAANG mural: bird, fish and bear. Amber black arched glazing, timber benches and round cafe tables.',limits:'Mural crops preserve real artwork with photographed shadows and some obstructions; not a seamless complete mural scan.'},
 {id:'degrassi-bend-2026',frames:['Video reference','Video reference','Video reference','Video reference','Video reference'],place:'Lower De Grassi bend /16–18',observed:'Green construction hoarding and mesh gate along east side, concrete rail edge above, SLOW diamond at the hedge. Number16 visible on rubble-stone pair, shared gable above paired entrances, navy canopy and steps, white flower boxes and red Japanese maple.',limits:'Hoarding extent estimated against mapped roadway; no current surveyed construction plan. Front dimensions estimated from video; no hidden rear reconstruction.'},
 {id:'logan-west',frames:['Video reference','Video reference','Video reference'],place:'875 Queen E / southwest Logan corner',observed:'Three-storey retained red-brick Starbucks corner; five upper openings; pale horizontal bands and dark bracketed cornice. New red/rose-brick apartment volume steps above it. Deep charcoal glazing surrounds, Juliet rails; orange A&W, green freshii, red signage and Pet Valu at the west end.',limits:'Upper-storey setbacks and heights estimated from video and map, not surveyed.'},
 {id:'logan-east',frames:['Video reference','Video reference','Video reference'],place:'889–893 Queen E / southeast Logan corner',observed:'Three-storey red-brick corner; Purple Penguin Coffee ground floor and visible 889 number; round-headed top windows, wider segmental middle openings, long Logan side with arched upper windows and wall AC units. Leslieville Cheese Market at891, Rowe Farms at893 with darker brick, wide segmental openings, sage shop glazing, grey fascia, a rainbow bench and teal planter.',limits:'Bay spacing and unseen eastern/rear elevations approximate.'},
 {id:'td',frames:['Video reference','Video reference'],place:'904 Queen E / northwest Logan corner',observed:'Buff brick, tall stone base, green individual awnings, recessed metal-framed door, stairs and accessible side ramp; shallow framed ATM and projecting green TD sign.',limits:'Upper facade outside the video frame remains inferred.'},
 {id:'north-shops',frames:['Video reference','Video reference','Video reference','Video reference'],place:'North sidewalk east of Booth',observed:'La Bamboche at892: beige bakery front and frosted name band. Matcha Haus at890: green timber storefront and yellow arrow. Hooked at888: grey display front and red canopy. The Roy at894: charcoal paint and orange-backed framed menu. Long ornamental iron fence. Grey tree planters with red rims; service pipes, ring bicycle stands, concrete slabs and brick edge strip.',limits:'Addresses corroborated by current business sites. Roy full front supplemented by an older official exterior photo. Upper elevations remain inferred; the complete Castle facade is not video-verified.'},
 {id:'woodgreen',frames:['Video reference','Video reference','Video reference'],place:'835 Queen E / south side of Booth',observed:'Long buff panel-clad institutional block, small irregular white-framed windows, shallow green roof cap, white ground level and round piers.',limits:'Plan from City footprint; exact window spacing and rear elevations approximate.'},
 {id:'park-booth',frames:['Video reference','Video reference','Video reference','Video reference'],place:'Jimmie Simpson Park, Queen/Booth entrance',observed:'Broad interlocking-paver entrance, low white planting walls, large burgundy park-name slab, tall brown drinking fountain, timber benches, yellow flowers and mature irregular tree canopy. Booth crosses in front of the entrance.',limits:'Plant species, measured heights and hidden paths remain approximate.'},
];
